name: Generate ASCII Artwork

on:
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v5

            - name: Install Cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Execute Cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

            - name: Sleep 30 Seconds
              run: sleep 30

    test_job_2:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v5

            - name: Sleep 10 Seconds
              run: sleep 10

            - name: Test file Exists
              run: grep -i "dragon" dragon.txt

    deploying_job_3:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v5
              
            - name: Read File
              run: cat dragon.txt

            - name: Deploy
              run: echo Deploying ... .. .